version: "3.9"

services:

  app:

    build: .

    container_name: my_app

    ports:

      - "8080:8080"   # map host:container (change according to your app)

  db:
    image: mysql:8.0

    container_name: my_mysql

    restart: always

    environment:

      MYSQL_ROOT_PASSWORD: example

      MYSQL_DATABASE: mydb

    ports:

      - "3306:3306"

    volumes:

      - db_data:/var/lib/mysql


volumes:

  db_data: